Update README.md with clearer instructions
Azure-Samples/serverless-chat-langchainjs pull request #47
Opened 2024-04-16 12:12 UTC by juliamuiruri4

This pull request primarily involves updates to the `README.md` file to improve clarity and provide more detailed instructions. 

## Purpose
Key changes:

* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L35-R35): The sample data description now specifies that the documents are in .pdf and markdown format.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R78-R82): The command to clone the repo is now presented in a more readable format.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L103-R104): The requirements for running the sample locally with Ollama now include sufficient disk space.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L119-R126): The instructions for starting the application and uploading the PDF documents have been made more explicit.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L161-R162): The Azure prerequisites section no longer includes a link for Azure for Students. - Considering Azure OpenAI isn't yet available in the Azure for Students free subscription, so I think having it under pre-requisites would set a wrong expectation to those using the subscription.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type

What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

2024-04-16 14:25 UTC, sinedied requested changes
Thanks for the PR! There are few small parts to fix, but this is definitely helpful!

2024-04-16 14:25 UTC, sinedied commented on README.md
> +We provide sample data to make this sample ready to try, but feel free to replace it with your own. We use a fictitious company called _Contoso Real Estate_, and the experience allows its customers t
we only have PDFs here, markdown is not support in this sample

2024-04-16 14:25 UTC, sinedied commented on README.md
> +- **Azure account**. If you're new to Azure, [get an Azure account for free](https://azure.microsoft.com/free) to get free Azure credits to get started.
We'd like to keep the specific addition for Students, as they don't have to use a credit card with the Azure for Students offer

2024-04-16 14:25 UTC, sinedied commented on README.md
> +If you have a machine with enough resources (sufficient disk space), you can run this sample entirely locally without using any cloud resources. To do that, you first have to install [Ollama](https:/
it's not disk space, but rather a supported CPU/GPU for inference

2024-04-17 08:38 UTC, juliamuiruri4 commented on README.md
> +We provide sample data to make this sample ready to try, but feel free to replace it with your own. We use a fictitious company called _Contoso Real Estate_, and the experience allows its customers t
Sorry, reverted this

2024-04-17 08:39 UTC, juliamuiruri4 commented on README.md
> +If you have a machine with enough resources (sufficient disk space), you can run this sample entirely locally without using any cloud resources. To do that, you first have to install [Ollama](https:/
Got it. I've removed the specification on resource

2024-04-19 12:18 UTC, sinedied approved these changes

2024-04-19 12:19 UTC, merged

2024-04-19 12:19 UTC, sinedied commented
Thanks @juliamuiruri4 !