(fix): AI Gallery Standard Validation
Azure-Samples/serverless-chat-langchainjs pull request #88
Opened 2024-07-09 14:46 UTC by glaucia86

Related to issue #87

Address the AI Gallery Standard Validation issues by updating the `README.md`, `.github/workflows/stale-bot.yml`, and adding `azure-dev.yaml`.

* **README.md**:
  - Add "Features" section.
  - Add "Getting Started" section.
  - Add "Guidance" section.

* **.github/workflows/stale-bot.yml**:
  - Add `microsoft/security-devops-action` to the steps.
  - Add `github/codeql-action/upload-sarif` to the steps.

* **azure-dev.yaml**:
  - Add `azure-dev.yaml` file with necessary configurations.

2024-07-09 15:30 UTC, sinedied commented on .github/workflows/stale-bot.yml
> +
I'm not sure why you run this here?
This is the workflow to warn for stale issues, the security workflow runs on commits here: https://github.com/Azure-Samples/serverless-chat-langchainjs/blob/main/.github/workflows/validate-infra.yaml

2024-07-09 15:30 UTC, sinedied commented on README.md
> +## Features
```suggestion
### Features
```

2024-07-09 15:30 UTC, sinedied commented on azure-dev.yaml
`azd` uses `azure.yaml` file, why duplicate the file here?

2024-07-09 15:32 UTC, sinedied commented on azure-dev.yaml
Looking into the issue, it's about the `deploy.yaml` workflow to be renamed `azure-dev.yaml`

2024-07-09 19:08 UTC, glaucia86 commented on .github/workflows/stale-bot.yml
> +
removed the file. I didn't noticed that. :P

2024-07-09 19:18 UTC, glaucia86 commented on azure-dev.yaml
Renamed file names from `deploy.yaml` to `azure-dev.yaml`

2024-07-10 12:36 UTC, sinedied requested changes

2024-07-10 12:36 UTC, sinedied commented on azure-dev.yaml
I see you've renamed the workflow, this file is not needed then

2024-07-10 12:36 UTC, sinedied commented on .github/workflows/stale-bot.yml
Could you restore the original file?

It's only a warning, and a false positive one. I'll ping the folks working on the automated scan for this one

2024-07-10 15:10 UTC, glaucia86 commented on azure-dev.yaml
So, before proceeding, because the explanation above wasn't very clear: should I remove this file, @sinedied?

2024-07-10 15:18 UTC, glaucia86 commented on .github/workflows/stale-bot.yml
Okay. Just so I have a clearer understanding of what to do here. It would be:

+ Restore this file `stale-bot.yml`
+ And inside of this file it would be:

```yaml
name: Close stale issues and PRs
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this issue will be closed.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity.'
          days-before-issue-stale: 60
          days-before-pr-stale: 60

      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@preview
        id: msdo
        continue-on-error: true
        with:
          tools: templateanalyzer

      - name: Upload alerts to Security tab
        if: github.repository_owner == 'Azure-Samples'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
```

But I should remove this `step` here, right?

```yaml

      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this issue will be closed.'
          stale-pr-message: 'This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed.'
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity.'
          days-before-issue-stale: 60
          days-before-pr-stale: 60
```

**[Link](https://github.com/Azure-Samples/serverless-chat-langchainjs/blob/3c4bc12232590eba0a02d808cdb3873116324a2b/.github/workflows/stale-bot.yml#L14)**

cc: @sinedied

2024-07-11 14:07 UTC, sinedied commented on .github/workflows/stale-bot.yml
no, you should restore the file to its state before this PR: we want to keep the stale actions, and only this. The security checks are done in a different workflow

2024-07-11 14:09 UTC, sinedied commented on azure-dev.yaml
Yes: the issue was only referring to the file `.github/workflows/azure-dev.yaml`, which you fixed by renaming the `deploy.yaml` workflow.

This file (`/azure-dev.yaml`) is not needed and can be removed, as it's only `azure.yaml` that is used by AZD cli.

2024-07-12 03:43 UTC, glaucia86 commented on azure-dev.yaml
Thanks for the clarification. Thanks, Yohan :)

2024-07-12 03:45 UTC, glaucia86 commented on .github/workflows/stale-bot.yml
File recovered

2024-07-12 13:05 UTC, sinedied approved these changes

2024-07-12 13:05 UTC, merged

2024-07-12 13:05 UTC, sinedied commented
Thanks!